// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace POS.Domain.Entities;

[Table("Config")]
public partial class Config
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [StringLength(1000)]
    [Unicode(false)]
    public string Value { get; set; }
}