// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class GetTotalSalesPerCustomerMonthlyResult
    {
        [StringLength(100)]
        public string? Item { get; set; }
        [Column("Quantity", TypeName = "decimal(38,2)")]
        public decimal? Quantity { get; set; }
        [Column("TotalSalesAmount", TypeName = "decimal(38,2)")]
        public decimal? TotalSalesAmount { get; set; }
    }
}
