// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetPerCustomerPerYearResult
    {
        [StringLength(100)]
        public string? CatalogName { get; set; }
        public int CatalogID { get; set; }
        [Column("Januari", TypeName = "decimal(38,2)")]
        public decimal? Januari { get; set; }
        [Column("Februari", TypeName = "decimal(38,2)")]
        public decimal? Februari { get; set; }
        [Column("Maret", TypeName = "decimal(38,2)")]
        public decimal? Maret { get; set; }
        [Column("April", TypeName = "decimal(38,2)")]
        public decimal? April { get; set; }
        [Column("Mei", TypeName = "decimal(38,2)")]
        public decimal? Mei { get; set; }
        [Column("Juni", TypeName = "decimal(38,2)")]
        public decimal? Juni { get; set; }
        [Column("Juli", TypeName = "decimal(38,2)")]
        public decimal? Juli { get; set; }
        [Column("Agustus", TypeName = "decimal(38,2)")]
        public decimal? Agustus { get; set; }
        [Column("September", TypeName = "decimal(38,2)")]
        public decimal? September { get; set; }
        [Column("Oktober", TypeName = "decimal(38,2)")]
        public decimal? Oktober { get; set; }
        [Column("November", TypeName = "decimal(38,2)")]
        public decimal? November { get; set; }
        [Column("Desember", TypeName = "decimal(38,2)")]
        public decimal? Desember { get; set; }
    }
}
