// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetHPPTablePerMonthResult
    {
        public long CatalogId { get; set; }
        [StringLength(100)]
        public string CatalogName { get; set; }
        [Column("col1", TypeName = "decimal(18,2)")]
        public decimal? col1 { get; set; }
        [Column("col2", TypeName = "decimal(18,2)")]
        public decimal? col2 { get; set; }
        [Column("col3", TypeName = "decimal(18,2)")]
        public decimal? col3 { get; set; }
        [Column("col4", TypeName = "decimal(18,2)")]
        public decimal? col4 { get; set; }
        [Column("col5", TypeName = "decimal(18,2)")]
        public decimal? col5 { get; set; }
        [Column("col6", TypeName = "decimal(18,2)")]
        public decimal? col6 { get; set; }
        [Column("col7", TypeName = "decimal(18,2)")]
        public decimal? col7 { get; set; }
        [Column("col8", TypeName = "decimal(18,2)")]
        public decimal? col8 { get; set; }
        [Column("col9", TypeName = "decimal(18,2)")]
        public decimal? col9 { get; set; }
        [Column("col10", TypeName = "decimal(18,2)")]
        public decimal? col10 { get; set; }
        [Column("col11", TypeName = "decimal(18,2)")]
        public decimal? col11 { get; set; }
        [Column("col12", TypeName = "decimal(18,2)")]
        public decimal? col12 { get; set; }
        [Column("col13", TypeName = "decimal(18,2)")]
        public decimal? col13 { get; set; }
        [Column("col14", TypeName = "decimal(18,2)")]
        public decimal? col14 { get; set; }
        [Column("col15", TypeName = "decimal(18,2)")]
        public decimal? col15 { get; set; }
        [Column("col16", TypeName = "decimal(18,2)")]
        public decimal? col16 { get; set; }
        [Column("col17", TypeName = "decimal(18,2)")]
        public decimal? col17 { get; set; }
        [Column("col18", TypeName = "decimal(18,2)")]
        public decimal? col18 { get; set; }
        [Column("col19", TypeName = "decimal(18,2)")]
        public decimal? col19 { get; set; }
        [Column("col20", TypeName = "decimal(18,2)")]
        public decimal? col20 { get; set; }
        [Column("col21", TypeName = "decimal(18,2)")]
        public decimal? col21 { get; set; }
        [Column("col22", TypeName = "decimal(18,2)")]
        public decimal? col22 { get; set; }
        [Column("col23", TypeName = "decimal(18,2)")]
        public decimal? col23 { get; set; }
        [Column("col24", TypeName = "decimal(18,2)")]
        public decimal? col24 { get; set; }
        [Column("col25", TypeName = "decimal(18,2)")]
        public decimal? col25 { get; set; }
        [Column("col26", TypeName = "decimal(18,2)")]
        public decimal? col26 { get; set; }
        [Column("col27", TypeName = "decimal(18,2)")]
        public decimal? col27 { get; set; }
        [Column("col28", TypeName = "decimal(18,2)")]
        public decimal? col28 { get; set; }
        [Column("col29", TypeName = "decimal(18,2)")]
        public decimal? col29 { get; set; }
        [Column("col30", TypeName = "decimal(18,2)")]
        public decimal? col30 { get; set; }
        [Column("col31", TypeName = "decimal(18,2)")]
        public decimal? col31 { get; set; }
    }
}
