// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetReconcileByIDResult
    {
        public long ID { get; set; }
        public DateTime? ProccessDate { get; set; }
        [StringLength(5000)]
        public string? Description { get; set; }
        [StringLength(100)]
        public string? purchaseno { get; set; }
        [StringLength(100)]
        public string? transactionid { get; set; }
    }
}
