// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetPrevillageByProfileResult
    {
        [StringLength(100)]
        public string Profile { get; set; } = default!;
        [StringLength(50)]
        public string Username { get; set; } = default!;
        [StringLength(100)]
        public string? Role { get; set; }
        [StringLength(100)]
        public string Menu { get; set; } = default!;
        public int MenuID { get; set; }
        public int RoleID { get; set; }
        public bool? AllowCreate { get; set; }
        public bool? AllowRead { get; set; }
        public bool? AllowUpdate { get; set; }
        public bool? AllowDelete { get; set; }
        public bool? AllowPrint { get; set; }
    }
}
