// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetCatalogItemResult
    {
        public int ID { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public string Description { get; set; }
        public string Notes { get; set; }
        public byte[] Photo { get; set; }
        [StringLength(20)]
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        [StringLength(20)]
        public string ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        [StringLength(10)]
        public string Unit { get; set; }
        [StringLength(20)]
        public string type { get; set; }
    }
}
