// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetCatalogPriceResult
    {
        public int ID { get; set; }
        public int? CatalogID { get; set; }
        [Column("BuyPricePerunit", TypeName = "decimal(18,2)")]
        public decimal? BuyPricePerunit { get; set; }
        [Column("SellPrice", TypeName = "decimal(18,2)")]
        public decimal? SellPrice { get; set; }
        public DateTime? PriceDate { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [StringLength(50)]
        public string SupplierCode { get; set; }
        [StringLength(500)]
        public string SupplierName { get; set; }
        [StringLength(100)]
        public string CatalogName { get; set; }
    }
}
