// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetPrevBuyPricesResult
    {
        public int CatalogID { get; set; }
        [StringLength(100)]
        public string? CatalogName { get; set; }
        [StringLength(10)]
        public string? Unit { get; set; }
        [Column("TotalBuyPrice", TypeName = "decimal(38,2)")]
        public decimal? TotalBuyPrice { get; set; }
        [Column("TotalQty", TypeName = "decimal(38,2)")]
        public decimal? TotalQty { get; set; }
        [Column("TotalPrice", TypeName = "decimal(38,2)")]
        public decimal? TotalPrice { get; set; }
        [Column("BuyPrice", TypeName = "decimal(38,6)")]
        public decimal? BuyPrice { get; set; }
        public DateOnly? TransDate { get; set; }
        public int? TotalItem { get; set; }
    }
}
