// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetActiveCatalogStockByCatalogIDResult
    {
        public int? CatalogID { get; set; }
        [Column("Stock", TypeName = "decimal(18,2)")]
        public decimal? Stock { get; set; }
        public DateOnly? StockDate { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public int IsActive { get; set; }
        [Column("colly", TypeName = "decimal(18,2)")]
        public decimal? colly { get; set; }
    }
}
