// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetTotalDailyPurchaseDetailResult
    {
        public DateTime? Tgl { get; set; }
        [StringLength(100)]
        public string NoTransaksi { get; set; }
        [StringLength(500)]
        public string Supplier { get; set; }
        [StringLength(100)]
        public string Item { get; set; }
        [Column("Qty", TypeName = "decimal(18,2)")]
        public decimal? Qty { get; set; }
        [Column("Harga", TypeName = "decimal(18,2)")]
        public decimal? Harga { get; set; }
    }
}
