// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetLogPagingResult
    {
        public DateTime LogDate { get; set; }
        [StringLength(100)]
        public string? ComputerName { get; set; }
        [StringLength(15)]
        public string? IPAddress { get; set; }
        [StringLength(50)]
        public string? LogType { get; set; }
        [StringLength(2147483647)]
        public string? LogMessage { get; set; }
        [StringLength(100)]
        public string? Username { get; set; }
        public int? RowIndex { get; set; }
    }
}
