// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetTotalPurchasesPerSupplierDailyResult
    {
        [StringLength(500)]
        public string? Supplier { get; set; }
        [StringLength(50)]
        public string SupplierCode { get; set; } = default!;
        public DateOnly? PurchaseDate { get; set; }
        [Column("TotalAmount", TypeName = "decimal(38,2)")]
        public decimal? TotalAmount { get; set; }
    }
}
