// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetSaleByTransactionIDResult
    {
        [StringLength(50)]
        public string TransactionID { get; set; }
        [Column("TotalPrice", TypeName = "decimal(18,2)")]
        public decimal? TotalPrice { get; set; }
        [StringLength(1000)]
        public string TotalQty { get; set; }
        public DateTime TransactionDate { get; set; }
        [StringLength(50)]
        public string Username { get; set; }
        public int? MemberID { get; set; }
        [StringLength(50)]
        public string Terminal { get; set; }
        [Column("TotalPayment", TypeName = "decimal(18,2)")]
        public decimal? TotalPayment { get; set; }
        [Column("TotalPaymentReturn", TypeName = "decimal(18,2)")]
        public decimal? TotalPaymentReturn { get; set; }
        [StringLength(2147483647)]
        public string Notes { get; set; }
        public int? PaymentType { get; set; }
        public DateTime? UpdatedDate { get; set; }
        [StringLength(50)]
        public string UpdatedBy { get; set; }
        public DateTime? ExpiredDate { get; set; }
        public DateTime? Created { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        public long Counter { get; set; }
    }
}
