// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetTotalSalePermonthResult
    {
        [Column("TotalSale", TypeName = "decimal(38,2)")]
        public decimal? TotalSale { get; set; }
        public DateTime? TransDate { get; set; }
    }
}
