// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetTotalPurchasesPerSupplierMonthlyResult
    {
    }
}
