// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetUserPagingResult
    {
        [StringLength(50)]
        public string Username { get; set; }
        [StringLength(1000)]
        public string Password { get; set; }
        public DateTime? LastLogin { get; set; }
        public bool? IsLogin { get; set; }
        [StringLength(15)]
        public string IPAddress { get; set; }
        [StringLength(100)]
        public string MachineName { get; set; }
        public bool? IsActive { get; set; }
        public int RowIndex { get; set; }
    }
}
