// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetUnitPagingResult
    {
        [StringLength(10)]
        public string? Code { get; set; }
        [StringLength(500)]
        public string? Name { get; set; }
        public int? RowIndex { get; set; }
    }
}
