// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetReconcileDetailByReconcileIDResult
    {
        public long ID { get; set; }
        public int? CatalogID { get; set; }
        [Column("CatalogQty", TypeName = "decimal(18,2)")]
        public decimal? CatalogQty { get; set; }
        [Column("CatalogPrice", TypeName = "decimal(18,2)")]
        public decimal? CatalogPrice { get; set; }
        public int? ProductID { get; set; }
        [Column("ProductPrice", TypeName = "decimal(18,2)")]
        public decimal? ProductPrice { get; set; }
        [Column("ProductQty", TypeName = "decimal(18,2)")]
        public decimal? ProductQty { get; set; }
        [StringLength(100)]
        public string? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        [StringLength(100)]
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
        public long? ReconcileID { get; set; }
        public DateTime? CatalogPriceDate { get; set; }
    }
}
