// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetPiutangResult
    {
        public long? CustomerID { get; set; }
        [StringLength(500)]
        public string CustomerName { get; set; }
        [StringLength(50)]
        public string TransactionID { get; set; }
        public DateTime TransDate { get; set; }
        [Column("TotalPrice", TypeName = "decimal(18,2)")]
        public decimal? TotalPrice { get; set; }
        [Column("TotalPayment", TypeName = "decimal(18,2)")]
        public decimal? TotalPayment { get; set; }
        [Column("Piutang", TypeName = "decimal(19,2)")]
        public decimal? Piutang { get; set; }
        public DateTime? ExpiredDate { get; set; }
    }
}
