// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetPerCustomerPerMonthResult
    {
        [StringLength(100)]
        public string? CatalogName { get; set; }
        public int CatalogID { get; set; }
        [Column("Col01", TypeName = "decimal(38,2)")]
        public decimal? Col01 { get; set; }
        [Column("Col02", TypeName = "decimal(38,2)")]
        public decimal? Col02 { get; set; }
        [Column("Col03", TypeName = "decimal(38,2)")]
        public decimal? Col03 { get; set; }
        [Column("Col04", TypeName = "decimal(38,2)")]
        public decimal? Col04 { get; set; }
        [Column("Col05", TypeName = "decimal(38,2)")]
        public decimal? Col05 { get; set; }
        [Column("Col06", TypeName = "decimal(38,2)")]
        public decimal? Col06 { get; set; }
        [Column("Col07", TypeName = "decimal(38,2)")]
        public decimal? Col07 { get; set; }
        [Column("Col08", TypeName = "decimal(38,2)")]
        public decimal? Col08 { get; set; }
        [Column("Col09", TypeName = "decimal(38,2)")]
        public decimal? Col09 { get; set; }
        [Column("Col10", TypeName = "decimal(38,2)")]
        public decimal? Col10 { get; set; }
        [Column("Col11", TypeName = "decimal(38,2)")]
        public decimal? Col11 { get; set; }
        [Column("Col12", TypeName = "decimal(38,2)")]
        public decimal? Col12 { get; set; }
        [Column("Col13", TypeName = "decimal(38,2)")]
        public decimal? Col13 { get; set; }
        [Column("Col14", TypeName = "decimal(38,2)")]
        public decimal? Col14 { get; set; }
        [Column("Col15", TypeName = "decimal(38,2)")]
        public decimal? Col15 { get; set; }
        [Column("Col16", TypeName = "decimal(38,2)")]
        public decimal? Col16 { get; set; }
        [Column("Col17", TypeName = "decimal(38,2)")]
        public decimal? Col17 { get; set; }
        [Column("Col18", TypeName = "decimal(38,2)")]
        public decimal? Col18 { get; set; }
        [Column("Col19", TypeName = "decimal(38,2)")]
        public decimal? Col19 { get; set; }
        [Column("Col20", TypeName = "decimal(38,2)")]
        public decimal? Col20 { get; set; }
        [Column("Col21", TypeName = "decimal(38,2)")]
        public decimal? Col21 { get; set; }
        [Column("Col22", TypeName = "decimal(38,2)")]
        public decimal? Col22 { get; set; }
        [Column("Col23", TypeName = "decimal(38,2)")]
        public decimal? Col23 { get; set; }
        [Column("Col24", TypeName = "decimal(38,2)")]
        public decimal? Col24 { get; set; }
        [Column("Col25", TypeName = "decimal(38,2)")]
        public decimal? Col25 { get; set; }
        [Column("Col26", TypeName = "decimal(38,2)")]
        public decimal? Col26 { get; set; }
        [Column("Col27", TypeName = "decimal(38,2)")]
        public decimal? Col27 { get; set; }
        [Column("Col28", TypeName = "decimal(38,2)")]
        public decimal? Col28 { get; set; }
        [Column("Col29", TypeName = "decimal(38,2)")]
        public decimal? Col29 { get; set; }
        [Column("Col30", TypeName = "decimal(38,2)")]
        public decimal? Col30 { get; set; }
        [Column("Col31", TypeName = "decimal(38,2)")]
        public decimal? Col31 { get; set; }
    }
}
