// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetTotalSalePerDayResult
    {
        [Column("TotalSales", TypeName = "decimal(38,2)")]
        public decimal? TotalSales { get; set; }
        [Column("Qty", TypeName = "decimal(38,2)")]
        public decimal? Qty { get; set; }
        [StringLength(100)]
        public string? CatalogName { get; set; }
        public int? CatalogID { get; set; }
        public DateOnly? TransactionDate { get; set; }
        [StringLength(10)]
        public string? Unit { get; set; }
    }
}
