// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetAllCatalogStockByCatalogIDResult
    {
        public int CatalogID { get; set; }
        [StringLength(100)]
        public string CatalogName { get; set; }
        [StringLength(10)]
        public string Unit { get; set; }
        [Column("Stock", TypeName = "decimal(18,2)")]
        public decimal? Stock { get; set; }
        public DateOnly? StockDate { get; set; }
    }
}
