// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetTotalPurchasesPerSupplierMonthlyResult
    {
        [StringLength(100)]
        public string Item { get; set; }
        [Column("Quantity", TypeName = "decimal(38,2)")]
        public decimal? Quantity { get; set; }
        [Column("TotalPurchasesAmount", TypeName = "decimal(38,2)")]
        public decimal? TotalPurchasesAmount { get; set; }
    }
}
