// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetCurrentStockByCatalogIDAndDateResult
    {
        public int CatalogID { get; set; }
        [StringLength(100)]
        public string? CatalogName { get; set; }
        [StringLength(10)]
        public string? Unit { get; set; }
        [Column("Stock", TypeName = "decimal(38,2)")]
        public decimal? Stock { get; set; }
        public DateOnly? StockDate { get; set; }
        [Column("Coli", TypeName = "decimal(21,2)")]
        public decimal? Coli { get; set; }
    }
}
