// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetHPPPerMonthResult
    {
        public DateOnly TransDate { get; set; }
        [Column("TotalHPP", TypeName = "decimal(18,2)")]
        public decimal? TotalHPP { get; set; }
        public long CatalogId { get; set; }
        [Column("PrevStock", TypeName = "decimal(18,2)")]
        public decimal? PrevStock { get; set; }
        [Column("PrevHPP", TypeName = "decimal(18,2)")]
        public decimal? PrevHPP { get; set; }
        [Column("TotalQty", TypeName = "decimal(18,2)")]
        public decimal? TotalQty { get; set; }
        [Column("TotalPrice", TypeName = "decimal(18,2)")]
        public decimal? TotalPrice { get; set; }
        [StringLength(100)]
        public string? CatalogName { get; set; }
    }
}
