// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable enable

namespace POS.Domain.Entities
{
    public partial class Usp_GetUnitByProfileResult
    {
        [StringLength(6)]
        public string Code { get; set; } = default!;
        [StringLength(100)]
        public string? Name { get; set; }
        [StringLength(100)]
        public string Profile { get; set; } = default!;
        [StringLength(20)]
        public string? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        [StringLength(20)]
        public string? ModifiedBy { get; set; }
        public DateTime? ModifiedDate { get; set; }
    }
}
