// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetTotalSalePerCatalogResult
    {
        [Column("Sale", TypeName = "decimal(38,2)")]
        public decimal? Sale { get; set; }
        [Column("Quantity", TypeName = "decimal(38,2)")]
        public decimal? Quantity { get; set; }
        [StringLength(4000)]
        public string MONTH_YEAR { get; set; }
        [StringLength(4000)]
        public string TransDate { get; set; }
        [StringLength(100)]
        public string Item { get; set; }
        [StringLength(10)]
        public string Unit { get; set; }
        public int? ItemID { get; set; }
    }
}
