// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetSumGrossProfitYearlyResult
    {
        public int? Month { get; set; }
        public int Sequence { get; set; }
        public int? YEAR { get; set; }
        [Column("TotalSales", TypeName = "decimal(38,2)")]
        public decimal? TotalSales { get; set; }
        [Column("TotalGrossProfit", TypeName = "decimal(38,2)")]
        public decimal? TotalGrossProfit { get; set; }
    }
}
