// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace POS.Domain.Entities
{
    public partial class Usp_GetPrevillageByRoleMenuResult
    {
        public int MenuID { get; set; }
        public int RoleID { get; set; }
        public bool? AllowCreate { get; set; }
        public bool? AllowRead { get; set; }
        public bool? AllowUpdate { get; set; }
        public bool? AllowDelete { get; set; }
        public bool? AllowPrint { get; set; }
    }
}
